### ISSUE TITLE
build 'Stuff Ive Reviewed' page

### ISSUE THREAD

**Issue by jsgunn22** [Luis00809/Group-3-project#13]
This page will be populated with items in the "stuff ive reviewed" object from the localStorage

[design](https://www.figma.com/file/YGI7GFFgwXdkC2eLj7qggK/Vidya?type=design&node-id=6%3A1055&mode=design&t=GmoSwtgAdvL67auA-1)

**Comment by jacobrkovacs** [comment]
Added function to view stuff i've reviewed page
